server:
  port: 80
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-consumer-80
    prefer-ip-address: true
spring:
  application:
    name: microservicecloud-consumer

# 指定调用某个微服务使用哪种负载均衡策略 <client name>.ribbon.*
#MICROSERVICECLOUD-PROVIDER-DEPT:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule